server:
  port: 8080

spring:
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    # url: "jdbc:h2:mem:task" # H2 DB 연결 주소 (In-Memory Mode)
    url: "jdbc:h2:file:~/testdb" # H2 DB 연결 주소 (Embedded Mode)
    username: jin # H2 DB 접속 ID (사용자 지정)
    password: jin # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true # H2 Console 사용 여부
      path: /h2-console # H2 Console 접속 주소

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true
    # defer-datasource-initialization: true
    # database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: DEBUG
